// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DragBox: typeof import('./src/components/DragBox.vue')['default']
    DragItem: typeof import('./src/components/DragItem.vue')['default']
    EditorBase: typeof import('./src/components/EditorPanel/EditorBase.vue')['default']
    EditorPanel: typeof import('./src/components/EditorPanel/EditorPanel.vue')['default']
    EditorSample: typeof import('./src/components/EditorPanel/EditorSample.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileSet: typeof import('./src/components/fileSet.vue')['default']
    HeaderItem: typeof import('./src/components/EditorPanel/HeaderItem.vue')['default']
    MonacoEditor: typeof import('./src/components/EditorPanel/MonacoEditor/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VariableTable: typeof import('./src/components/VariableTable.vue')['default']
    WebDebugger: typeof import('./src/components/webDebugger.vue')['default']
    WebTerminal: typeof import('./src/components/webTerminal.vue')['default']
  }
}
