version: "3.7"

services:
  frontend:
    image: cqqqwq/web_project_frontend
    container_name: "nginx-frontend"
    restart: "always"
    ports:
      - "80:80"
  backend:
    build: cqqqwq/web_project_backend
    container_name: "flask-backend"
    restart: "always"
    ports:
      - "5000:5000"

