# 服务器部署用：sudo docker compose up -d
version: "3.7"

services:
  frontend:
    image: cqqqwq/web_project_frontend
    container_name: "nginx-frontend"
    restart: "always"
    ports:
      - "80:80"
  backend:
    image: cqqqwq/web_project_backend
    container_name: "flask-backend"
    restart: "always"
    ports:
      - "5000:5000"
      - "30000:30000"
    volumes:
      - userfile:/app/userfile
      - userinfo:/app/userInfo

volumes:
  userfile:
  userinfo:

  # watchtower: # autoupdate image
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 30
