# 本地调试用，docker compose -f docker-compose.dev.yml up -d
version: "3.7"

services:
  frontend:
    build: ./frontend
    container_name: "nginx-frontend"
    restart: "always"
    ports:
      - "80:80"
  backend:
    build: ./backend
    container_name: "flask-backend"
    restart: "always"
    ports:
      - "5000:5000"